// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9j4Ei0j5_ob4cEHvqMK0aV4JleJlkDT8',
    appId: '1:759287515736:web:e8e713524e69abb3b3d82d',
    messagingSenderId: '759287515736',
    projectId: 'auth-demo-c3cf6',
    authDomain: 'auth-demo-c3cf6.firebaseapp.com',
    storageBucket: 'auth-demo-c3cf6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkaNAQ6qlUd7hUxACnq3do7Wk9Cy34OR0',
    appId: '1:759287515736:android:e59f01a6beb82aa4b3d82d',
    messagingSenderId: '759287515736',
    projectId: 'auth-demo-c3cf6',
    storageBucket: 'auth-demo-c3cf6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_pIqpVu4cJ3uVwSEGtahkxUyuU040Awo',
    appId: '1:759287515736:ios:000a5e52929be34eb3d82d',
    messagingSenderId: '759287515736',
    projectId: 'auth-demo-c3cf6',
    storageBucket: 'auth-demo-c3cf6.appspot.com',
    iosBundleId: 'com.example.authDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_pIqpVu4cJ3uVwSEGtahkxUyuU040Awo',
    appId: '1:759287515736:ios:000a5e52929be34eb3d82d',
    messagingSenderId: '759287515736',
    projectId: 'auth-demo-c3cf6',
    storageBucket: 'auth-demo-c3cf6.appspot.com',
    iosBundleId: 'com.example.authDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9j4Ei0j5_ob4cEHvqMK0aV4JleJlkDT8',
    appId: '1:759287515736:web:c9a8e8e7eb5a7ff3b3d82d',
    messagingSenderId: '759287515736',
    projectId: 'auth-demo-c3cf6',
    authDomain: 'auth-demo-c3cf6.firebaseapp.com',
    storageBucket: 'auth-demo-c3cf6.appspot.com',
  );
}
